### ISSUE TITLE
no significant DESeq2 results?

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#10]
In my [notebook](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-11-11-oly-gonad-OA-part4-differential-expression.ipynb), I used DESeq2 to analyze all of my count data. I then tried splitting it into pairwise comparisons to try and see if I could tease out where the differences were. When I did my pairwise comparisons, I had no significant results.

What should be my next steps after completing DESeq2?

**Comment by sr320** [comment]
Adjust p-value

**Comment by yaaminiv** [comment]
Is there a maximum acceptable p-value I shouldn't go any higher than?

**Comment by sr320** [comment]
No

**Comment by yaaminiv** [comment]
When I examined the adjusted p-values (p-adj) for each comparison in DESeq2, I found the following:
- Female_106 vs. Female_108: No p-adj less than 0.9996995
- Male_106 vs. Male_108: No p-adj less than 1
- Female_106 vs. Male_106: No p-adj less than 0.9996995
- Female_108 vs. Male_108: No p-adj less than 1

Setting my p-value to 1.0 is not useful. Now what?

**Comment by sr320** [comment]
link to notebook?

**Comment by yaaminiv** [comment]
https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-11-11-oly-gonad-OA-part4-differential-expression.ipynb

**Comment by sr320** [comment]
Did you do 106 and 106  v 108 and 108? if not try that

Also you can take DEG from sex differences and run downstream analysis...
enrichment, DAVID - Revigo

**Comment by yaaminiv** [comment]
I did 106 vs. 106 and 108 vs. 108! Those are the last two comparisons listed in my notebook. I still got no significant results. 

Do you think there's a problem with my count data? Was 20% standard deviation too high of an estimate? (notebook: https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-11-04-oly-gonad-OA-part3-kallisto.ipynb)

**Comment by sr320** [comment]
I mean the two 106 samples versus the two 108 samples

**Comment by sr320** [comment]
Re SD - try decreasing and running

**Comment by yaaminiv** [comment]
oh yes, that was the first thing I did (any resulting files are labelled "alltreatments.")! i did the analyses with p = .05 and p = .5

I'll rerun kallisto with SD = 10% and see if that changes anything

**Comment by yaaminiv** [comment]
I tried rerunning kallisto with SD = 10% and still got no significant results:

https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-11-29-oly-gonad-OA-part5-rerun-kallisto-and-DESeq2.ipynb

What should my next steps be? What I can think of is either running a pairwise comparison between Female_106 and Male_108 to see if that's really where all the variation stems from, or trying `kallisto quant` with an extreme SD of 0

**Comment by sr320** [comment]
Then select a threshold to ID genes expressed differently. For example,
must have at least a total of 20 reads and there must be a 4-fold
difference.
