### ISSUE TITLE
gene ontology/enrichment analysis.

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#11]
I have a table of differentially expressed genes from DESeq2 and now I want to do gene ontology/enrichment analysis. I'm assuming my first step would be combining my table of differentially expressed genes with the [blastx table of best matches that has gene ontology information](https://raw.githubusercontent.com/yaaminiv/yaaminiv-fish546-2016/master/analyses/blastx-11-14-best-matches)?

After this, would I just put in the information in ReViGo/GoSlim and pull out anything that looks interesting?

**Comment by sr320** [comment]
You take UniProt accessions from DEG, and accessions from all...
And use DAVID.
from week 4  - https://www.youtube.com/watch?v=D2XjF2xqbF4&feature=youtu.be

also please post these on course repo, as others have done this / could
benefit from answer.
