### ISSUE TITLE
Week 4 Project Review

### ISSUE THREAD

**Issue by sr320** [yaaminiv/yaaminiv-fish546-2016#2]
Here is a personalized video review

https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=31527f5c-5c77-42a3-9373-b85fd4a3d9b1

Take home in terms of primary steps to undertake (on a lab computer)
1) Get blastx started on Transcriptome (fasta file) 😃  to compare to Uniprot-Swiss-Prot
2) Run program such as Kallisto to get count data for you libraries.

Let me know if you need help getting set up on a lab computer and/or question about how to tackle 1 and 2.
thanks!

**Comment by yaaminiv** [comment]
Thank you! I'd like to try doing the blastx on a lab computer. I tried using my machine but it kept timing out. Before I use a lab computer, is there anything I need to do first?

**Comment by sr320** [comment]
I would get Kallisto going at the same time. If you have time in the next 20 minutes I can show you the computer to use etc...

**Comment by yaaminiv** [comment]
great I'll pop by your office now.

**Comment by yaaminiv** [comment]
just in terms of workflow...would it be better to run kallisto with trimmed sequences? or is it fine to include adapters?

**Comment by sr320** [comment]
Fine to run raw reads
