### ISSUE TITLE
jupyter notebook command on genefish

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#3]
I tried using the command `jupyter notebook` in terminal but I got an error message that said the jupyter command was not found. Since Anaconda is already downloaded on the computer in the shared folder, do I need to change my directory in order to use this command?

**Comment by sr320** [comment]
Try ipython notebook

**Comment by yaaminiv** [comment]
`iPhython notebook` works! but now I'm having trouble uploading the notebook from my repo. I get the following message: "No handlers could be found for logger "tornado.general"

**Comment by sr320** [comment]
Start a new notebook- see if that works

**Comment by yaaminiv** [comment]
making a new notebook works. does this mean that I have to start a new notebook on every new machine? or is this just a problem getting jupyter notebooks in iphython?

**Comment by sr320** [comment]
Ask in class tomorrow

**Comment by yaaminiv** [comment]
I solved the issue by downloading the most recent version of anaconda and opening jupyter notebook through the anaconda navigator!
