### ISSUE TITLE
running multiple notebooks on a remote machine

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#4]
I'm trying to open a new notebook to run kallisto simultaneously with a blast, but it's really laggy (terminal keeps telling me that the web socket is timing out). obviously can't change much right now, but how can I prevent this from happening again?

**Comment by sr320** [comment]
Limit threads (cpus) of blast

**Comment by sr320** [comment]
Actually you are only using 1 cpu now. And limited ram. So it should work just fine
Try to just run in terminal instead of jupyter.
