### ISSUE TITLE
terminal error during blast

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#5]
![websockettimeout](https://cloud.githubusercontent.com/assets/22335838/20011070/9c49594c-a267-11e6-96c1-3213b3534980.png)

I keep getting the following error message whenever I try to complete my blastx. I think it's preventing my blastx from completing? Is this something `nohup` would fix?

**Comment by sr320** [comment]
That appears to be a jupyter  error. 
I would try running blast directly in terminal.

Curious- so  you are not launching using `jupyter notebook`?

**Comment by yaaminiv** [comment]
on my machine, i launch using `jupyter notebook` but on genefish i went through anaconda

**Comment by yaaminiv** [comment]
I started blastx in the terminal on my own machine yesterday afternoon and it's still not done...should I try on genefish? It's just weird to me that it's taking more than 24 hours to complete a blast

![screen shot 2016-11-07 at 3 35 44 pm](https://cloud.githubusercontent.com/assets/22335838/20080689/eb384190-a4ff-11e6-88f7-bd2cecb29961.png)

**Comment by sr320** [comment]
It could take weeks depending on query, database, and number of CPUs being
used.
How far did it get in 24 hours?

**Comment by yaaminiv** [comment]
I'm at TR24299, and I believe I have around 10,000 more sequences in the transcriptome to go?
