### ISSUE TITLE
corrupted notebook?

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#6]
![screen shot 2016-11-04 at 8 33 30 am](https://cloud.githubusercontent.com/assets/22335838/20011597/6f904d1e-a269-11e6-9f90-e71ddaa88cd6.png)

I'm not sure what happened, but now one of my notebooks won't open. Any suggestions on how to fix this?

**Comment by sr320** [comment]
I would start a new notebook-
Can you view on github.

Could be related to going back and forth across version / machines without regular commits..

**Comment by yaaminiv** [comment]
i can't view it on github! i can track back the commit where everything fell apart. if i go back and fix the problem, will it erase the work i did afterwards?

**Comment by yaaminiv** [comment]
i luckily was able to fix it by reverting 2 different commits! learned my lesson about opening 2 jupyter notebooks in 2 different machines the hard way.
