### ISSUE TITLE
additional arguments for kallisto 

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#7]
How would I get `-l` and `-s`?

![screen shot 2016-11-04 at 9 00 13 am](https://cloud.githubusercontent.com/assets/22335838/20012743/b474a6d8-a26d-11e6-825d-769adcd95d74.png)

**Comment by sr320** [comment]
Fastqc output

**Comment by yaaminiv** [comment]
I was able to get `-l` from the fastqc output, but i still don't have `-s`. it's not in the sequence length distribution or basic stats sections. is the standard deviation listed as something else?

**Comment by sr320** [comment]
Note above (your screenshot) those are not required but rather **optional**.

**Comment by yaaminiv** [comment]
The error message I got: `Error: fragment length mean and sd must be supplied for single-end reads using -l and -s`

Because I have single-end reads, kallisto wouldn't let me quantify abundance without both arguments. I used 20% for `-s` like you suggested and I was able to complete the analysis.

**Comment by sr320** [comment]
seem odd
I did not get any error
https://github.com/sr320/course-fish546-2016/blob/master/jupyter-nbs/005-RNA-seq.ipynb

**Comment by yaaminiv** [comment]
that's weird...not sure why I got an error then. 
![screen shot 2016-11-11 at 10 56 58 am](https://cloud.githubusercontent.com/assets/22335838/20226600/9ba8c676-a7fd-11e6-80b2-3f7d42b75979.png)

**Comment by sr320** [comment]
If using single end reads, you have to use `--single` argument. (see error
message)

**Comment by yaaminiv** [comment]
Yes, and when I did that it lead me to my original problem with `-l` and `-s`! 😅 

I'm not sure why you could run your analysis without specifying `--single` but I had to.
