### ISSUE TITLE
converting kallisto output to .txt file

### ISSUE THREAD

**Issue by yaaminiv** [yaaminiv/yaaminiv-fish546-2016#8]
my `kallisto quant` output is in a .tsv file. how can I convert it to a .txt file to use in DeSeq2?

(is going from kallisto to DeSeq2 even the next best step???)

**Comment by sr320** [comment]
What does kallisto output look like, and DESeq2 input look like?
Excel is fine...
`awk` could also be used to rearrange columns.

**Comment by yaaminiv** [comment]
i had no idea i could open a .tsv file in excel! the more you know 🌈
